/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119929-g8aa6df663e-20250621"
#endif /* AVUTIL_FFVERSION_H */
